# Generated by Django 5.0.4 on 2024-06-24 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum', models.BigIntegerField()),
                ('maximum', models.BigIntegerField()),
                ('apt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aptdb.apt')),
            ],
        ),
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.FloatField()),
                ('lat', models.FloatField()),
                ('apt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aptdb.apt')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=2083)),
                ('apt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aptdb.apt')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=2083)),
                ('apt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aptdb.apt')),
            ],
        ),
    ]
