# Generated by Django 5.0.4 on 2024-06-19 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aptdb', '0002_amounts_coords_images_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='apt',
        ),
        migrations.RemoveField(
            model_name='coords',
            name='apt',
        ),
        migrations.RemoveField(
            model_name='info',
            name='apt',
        ),
        migrations.DeleteModel(
            name='Amounts',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Coords',
        ),
        migrations.DeleteModel(
            name='Apt',
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
