# Generated by Django 5.0.4 on 2024-06-19 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aptdb', '0003_remove_images_apt_remove_coords_apt_remove_info_apt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Amounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum', models.BigIntegerField()),
                ('maximum', models.BigIntegerField()),
                ('apt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aptdb.apt')),
            ],
        ),
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.FloatField()),
                ('lat', models.FloatField()),
                ('apt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aptdb.apt')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=2083)),
                ('apt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aptdb.apt')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=2083)),
                ('apt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aptdb.apt')),
            ],
        ),
    ]
